apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-color-deployment-green
  labels:
    app: app-color
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-color
  template:
    metadata:
      labels:
        app: app-color
    spec:
      containers:
      - name: app-color
        image: jgmurua/app-color:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "32Mi"
        env:
        - name: BACKGROUND_COLOR
          value: "#64FE2E"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-color-deployment-red
  labels:
    app: app-color
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-color
  template:
    metadata:
      labels:
        app: app-color
    spec:
      containers:
      - name: app-color
        image: jgmurua/app-color:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "32Mi"
        env:
        - name: BACKGROUND_COLOR
          value: "#FF0000"
---
apiVersion: v1
kind: Service
metadata:
  name: app-color-service
  labels:
    app: app-color
spec:
  type: NodePort
  selector:
    app: app-color
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-color-ingress
  namespace: app-color
  labels:
    app: app-color
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: app-color-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP 
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
    # alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    # alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:xxxx
spec:
  ingressClassName: alb
  defaultBackend:
    service:
      name: app-color-service
      port:
        number: 80


